---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-local-storage
  annotations:
    # 設定為預設的 storage class
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.244.0.10:8080"
  clusterid: "4330013ebc7ca7498da59f999520403b"
  restauthenabled: "true"
  restuser: "admin"
  restuserkey: "123456"
  gidMin: "40000"
  gidMax: "50000"
  volumetype: "replicate:4"
allowVolumeExpansion: true

--- 

# # pvc.yml 
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: mysql-local-storage
#   annotations:
#     volume.beta.kubernetes.io/storage-class: "glusterfs"
# spec:
#   storageClassName: mysql-local-storage
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi