---
# deploy-base.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    # Apply this config only on the master.
    [mysqld]
    
  slave.cnf: |
    # Apply this config only on slaves.
    [mysqld]
    super-read-only
  my.cnf: |
    # mysql configuration file
    [mysqld]

    log-bin
    binlog_format = row
    gtid-mode = on
    enforce-gtid-consistency = on
    log-slave-updates
    secure_file_priv = /var/lib/mysql

    !includedir /etc/mysql/conf.d/
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - name: mysql-service
    port: 3306
  clusterIP: None
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-read-service
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    
---

# deploy-master.yml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-master
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        mysql: master
      initContainers:
      - name: init-mysql
        image: mysql:8.0.18
        command:
        - bash
        - "-c"
        - |
          set -ex
          # Generate mysql server-id from pod ordinal index.
          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          mkdir -p /mnt/mysql/conf.d
          echo [mysqld] > /mnt/mysql/conf.d/server-id.cnf
          # Add an offset to avoid reserved server-id=0 value.
          echo server-id=$((100 + ${BASH_REMATCH[1]})) >> /mnt/mysql/conf.d/server-id.cnf
          # Copy appropriate conf.d files from config-map to emptyDir.
          cp /mnt/config-map/master.cnf /mnt/mysql/conf.d/
          cp /mnt/config-map/my.cnf /mnt/mysql
        volumeMounts:
        - name: conf
          mountPath: /mnt/mysql
        - name: config-map
          mountPath: /mnt/config-map
      containers:
        - name: mysql
          image: mysql:8.0.18
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "mysql_pass"
            # TODO passwd
            #valueFrom:
            #  secretKeyRef:
            #    name: mysql-password
            #    key: root-password
          ports:
            - containerPort: 3306
          volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
          - name: conf
            mountPath: /etc/mysql
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            exec:
              command: ["mysqladmin", "-uroot", "-pmysql_pass", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              # Check we can execute queries over TCP (skip-networking is off).
              # TODO is passwrd
              command: ["mysql", "-h", "127.0.0.1", "-uroot", "-pmysql_pass", "-e", "SELECT 1"]
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
        - name: xtrabackup
          image: 47.108.235.230:8090/base/percona-xtrabackup:8.0
          ports:
            - containerPort: 3307
          env: 
            - name: BACKUP_ACCOUNT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: root-password
          command:
          - bash
          - "-c"
          - |
            set -ex
            
            cd /var/lib/mysql

            ls -l /var/lib/mysql

            [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
            exec ncat --listen --keep-open --send-only --max-conns=1 3307 -c \
            "xtrabackup --backup --slave-info --stream=xbstream --host=127.0.0.1 --user=root  --password=$(BACKUP_ACCOUNT_PASSWORD)"
          volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
          - name: conf
            mountPath: /etc/mysql
          - name: adduser
            mountPath: /data/mysql
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
      - name: conf
        emptyDir: {}
      - name: config-map
        configMap:
          name: mysql
      - name: adduser
        configMap:
          name: mysql-user
      imagePullSecrets:
        - name: image-repo-secret
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      #accessModes: ["ReadWriteMany"]
      storageClassName: mysql-local-storage
      resources:
        requests:
          storage: 1Gi

---

# deploy-slave.yml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-slave
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-service
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      #分布相差
      topologySpreadConstraints:
      - maxSkew: 1 #相差数量
        topologyKey: mysql
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
            matchLabels:
              app: mysql
      # nodeSelector:
      #   mysql: slave
      initContainers:
      - name: init-mysql
        image: mysql:8.0.18
        command:
        - bash
        - "-c"
        - |
          set -ex
          # Generate mysql server-id from pod ordinal index.
          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          mkdir -p /mnt/mysql/conf.d
          echo [mysqld] > /mnt/mysql/conf.d/server-id.cnf
          # Add an offset to avoid reserved server-id=0 value.
          echo server-id=$((200 + ${BASH_REMATCH[1]})) >> /mnt/mysql/conf.d/server-id.cnf
          # Copy appropriate conf.d files from config-map to emptyDir.
          cp /mnt/config-map/slave.cnf /mnt/mysql/conf.d/
          cp /mnt/config-map/my.cnf /mnt/mysql
        volumeMounts:
        - name: conf
          mountPath: /mnt/mysql
        - name: config-map
          mountPath: /mnt/config-map
      - name: clone-mysql
        image: 47.108.235.230:8090/base/percona-xtrabackup:8.0
        command:
        - bash
        - "-c"
        - |
          set -ex
          # Skip the clone if data already exists.
          [[ -f /var/lib/mysql/xtrabackup_binlog_info ]] && exit 0

          [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
          if [[ ${BASH_REMATCH[1]} -eq 0 ]]; then
            # Clone data from master
            ncat --recv-only mysql-master-0.mysql-service 3307 | xbstream -x -C /var/lib/mysql
          else 
            # Clone data from previous peer.
            ncat --recv-only mysql-slave-$((${BASH_REMATCH[1]}-1)).mysql-service 3307 | xbstream -x -C /var/lib/mysql
          fi
          
          # Prepare the backup.
          ls -l /var/lib/mysql
          xtrabackup --prepare --target-dir=/var/lib/mysql
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: conf
          mountPath: /etc/mysql
      containers:
        - name: mysql
          image: mysql:8.0.18
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "mysql_pass"
          ports:
            - containerPort: 3306
          volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
          - name: conf
            mountPath: /etc/mysql
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            exec:
              command: ["mysqladmin", "-uroot", "-pmysql_pass", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              # Check we can execute queries over TCP (skip-networking is off).
              command: ["mysql", "-h127.0.0.1", "-uroot", "-pmysql_pass", "-e", "SELECT 1"]
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
        - name: xtrabackup
          image: 47.108.235.230:8090/base/percona-xtrabackup:8.0
          ports:
            - containerPort: 3307
          env: 
            - name: ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: root-password
          command:
          - bash
          - "-c"
          - |
            set -ex
            cd /var/lib/mysql

            ls -l /var/lib/mysql

            # Check if we need to complete a clone by starting replication.
            #echo "Waiting for mysqld to be ready (accepting connections)"
            #until mysql -h 127.0.0.1 -e "SELECT 1"; do sleep 1; done

            # Determine binlog position of cloned data, if any
            if [[ -f xtrabackup_binlog_info ]]; then
              # We're cloning directly from master. Parse binlog position.
              echo "Initializing replication from clone position"
              [[ `cat xtrabackup_binlog_info` =~ ^(.*?)[[:space:]]+(.*?)$ ]] || exit 1
              echo "SET @@GLOBAL.GTID_PURGED='${BASH_REMATCH[2]}';" > set_gtid.sql
            fi

            # In case of container restart, attempt this at-most-once.
            echo "changing master..."
            mysql -h 127.0.0.1 -uroot -p$(ROOT_PASSWORD) <<EOF
              $(<set_gtid.sql)
              STOP SLAVE;
              CHANGE MASTER TO
              MASTER_HOST='mysql-master-0.mysql-service',
              MASTER_USER='root',
              MASTER_PASSWORD='$(ROOT_PASSWORD)',
              MASTER_CONNECT_RETRY=10,
              master_auto_position = 1,
              get_master_public_key=1;
              RESET SLAVE;
              START SLAVE;
            EOF

            # Start a server to send backups when requested by peers.
            exec ncat --listen --keep-open --send-only --max-conns=1 3307 -c \
            "xtrabackup --backup --slave-info --stream=xbstream --host=127.0.0.1 --user=root --password=$(ROOT_PASSWORD)"
          volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
          - name: conf
            mountPath: /etc/mysql
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
      volumes:
      - name: conf
        emptyDir: {}
      - name: config-map
        configMap:
          name: mysql
      imagePullSecrets:
        - name: image-repo-secret
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        volume.beta.kubernetes.io/storage-class: anything
    spec:
      accessModes: ["ReadWriteOnce"]
      #accessModes: ["ReadWriteMany"]
      storageClassName: mysql-local-storage
      resources:
        requests:
          storage: 1Gi