{
 "title": "Blackbox Exporter Dashboard",
 "description": "支持Grafana 8，基于blackbox_exporter 0.19.0设计；采用图表+曲线图方式展示TCP，ICMP，HTTPS的服务状态，各阶段请求延时，HTTPS证书信息等；优化展示效果，支持监控目标的分组、分类级联展示，多服务同时对比展示。",
 "tags": [ "StarsL.cn" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "module",
    "label": "类型",
    "query": {
     "query": "label_values(probe_success,job)"
    }
   },
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(probe_success{job=~\"$module\",company=~\"$company\",project=~\"$project\",env=~\"$env\",name=~\"$name\"},instance)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "target",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "状态明细",
   "type": "table",
   "gridPos": { "h": 30, "w": 23, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_success{job=~\"$module\"} - 0"
    },
    {
     "expr": "probe_http_status_code{job=~\"$module\"} - 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$module\"}-time())/3600/24"
    },
    {
     "expr": "probe_http_version{job=~\"$module\"} - 0"
    },
    {
     "expr": "probe_duration_seconds{job=~\"$module\"} - 0"
    },
    {
     "expr": "sum_over_time(probe_success{job=~\"$module\"}[60m])/count_over_time(probe_success{job=~\"$module\"}[60m])"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$module\"}"
    },
    {
     "expr": "probe_dns_lookup_time_seconds{job=~\"$module\"}-0"
    }
   ]
  },
  {
   "title": "HTTP 状态占比",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count_values('value',probe_http_status_code{job=~\"$module\"})"
    }
   ]
  },
  {
   "title": "连通性占比",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count_values('value',probe_success{job=~\"$module\"})"
    }
   ]
  },
  { "title": "$target status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }, "repeat": "target" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "SSL Expiry",
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
    }
   ]
  },
  {
   "title": "Average Probe Duration",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 13, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Average DNS Lookup",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Probe Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 41 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$target\"}",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "HTTP Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$target\"}"
    }
   ]
  },
  {
   "title": "HTTP Status Code",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$target\"}"
    }
   ]
  }
 ]
}