{
 "title": "1 Docker Dashboard",
 "description": "1 Docker Dashboard",
 "tags": [ "Docker" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Host:",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total, job)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{instance=~\"$server:(.*)\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "docker server",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace((count(container_cpu_load_average_10s{name!=\"\"}) by (instance)),\"ip\",\"$1\",\"instance\",\"(.*):.*\")"
    },
    {
     "expr": "label_replace((cadvisor_version_info),\"ip\",\"$1\",\"instance\",\"(.*):.*\")"
    },
    {
     "expr": "label_replace(((avg(irate(container_cpu_system_seconds_total{name!=\"\"}[1m]))by (instance) * 100)),\"ip\",\"$1\",\"instance\",\"(.*):.*\")"
    },
    {
     "expr": "label_replace((sum(container_memory_usage_bytes{name=~\".+\"}) by (instance)),\"ip\",\"$1\",\"instance\",\"(.*):.*\")"
    },
    {
     "expr": "label_replace((sum(container_fs_usage_bytes{name!=\"\"}) by (instance)),\"ip\",\"$1\",\"instance\",\"(.*):.*\")"
    },
    {
     "expr": "label_replace((sum(rate(container_network_receive_bytes_total{name!=\"\"}[1m])) by (instance)),\"ip\",\"$1\",\"instance\",\"(.*):.*\")"
    },
    {
     "expr": "label_replace((sum(rate(container_network_transmit_bytes_total{name!=\"\"}[1m])) by (instance)),\"ip\",\"$1\",\"instance\",\"(.*):.*\")"
    }
   ]
  },
  {
   "title": "docker con data",
   "type": "table",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{instance=~\"$server:.*\",name=~\".+\"}[$interval])) by (name) * 100"
    },
    {
     "expr": "sum(container_memory_rss{instance=~\"$server:.*\",name=~\".+\"}) by (name)"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{instance=~\"$server:.*\",name=~\".+\"}[$interval])) by (name)"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{instance=~\"$server:.*\",name=~\".+\"}[$interval])) by (name)"
    },
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{instance=~\"$server:$port\",job=~\"$job\",image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{instance=~\"$server:$port\",job=~\"$job\",image!=\"\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{instance=~\"$server:$port\",job=~\"$job\",image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{instance=~\"$server:$port\",job=~\"$job\",image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "I/O Rx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_reads_bytes_total{instance=~\"$server:$port\",job=~\"$job\",image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "I/O Tx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_writes_bytes_total{instance=~\"$server:$port\",job=~\"$job\",image!=\"\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}