{
 "title": "PostgreSQL Database",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "label": "Server", "query": { "query": "node_boot_time_seconds" } },
   { "name": "database", "label": "Database", "query": { "query": "pg_static" } }
  ]
 },
 "panels": [
  {
   "title": "==============================System Summary==============================",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "System Start Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_boot_time_seconds{instance=\"$server\"} * 1000",
     "legendFormat": "System Uptime(days)"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$server\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Usage (5m)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"$server\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU IO Wait (5m)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=\"$server\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"$server\"} - (node_memory_MemFree_bytes{instance=\"$server\"} + node_memory_Buffers_bytes{instance=\"$server\"} + node_memory_Cached_bytes{instance=\"$server\"})) / node_memory_MemTotal_bytes{instance=\"$server\"} * 100"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_Cached_bytes{instance=\"$server\"} * 100) / node_memory_MemTotal_bytes{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "System Average Load (1,5,15) ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$server\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=\"$server\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=\"$server\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance='$server',fstype=~\"ext3|ext4|xfs|nfs\"})/100 *100"
    },
    {
     "expr": "node_filesystem_avail_bytes {instance='$server',fstype=~\"ext3|ext4|xfs|nfs\"}"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance='$server',fstype=~\"ext3|ext4|xfs|nfs\"} / node_filesystem_size_bytes{instance='$server',fstype=~\"ext3|ext4|xfs|nfs\"})"
    }
   ]
  },
  {
   "title": "Disk Read/Write IOPS (1m)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "ops", "label": "reads(+)/ writes(-) " }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{device}}_reads"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{instance=~\"$server\"}[1m])",
     "legendFormat": "{{device}}_writes"
    },
    {
     "expr": "node_disk_io_now{instance=~\"$server\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "==============================Databsase Summary==============================",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true
  },
  {
   "title": "PostgreSQL Start Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_postmaster_start_time_seconds{instance=\"$database\"} * 1000"
    }
   ]
  },
  {
   "title": "PostgreSQL Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{instance=\"$database\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Shared_buffers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=\"$database\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Effective_cache_size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_effective_cache_size_bytes{instance=\"$database\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Work Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{instance=\"$database\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Max Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{instance=\"$database\"}"
    }
   ]
  },
  {
   "title": "Logging Collector",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_logging_collector{instance=\"$database\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Fsync",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_fsync{instance=\"$database\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL Database Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_database_size{instance=\"$database\",datname!~\"postgres|template0|template1\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Current Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "pg_stat_connetion_count", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "PostgreSQL Table Locks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "pg_locks_count{instance=\"$database\",datname!~\"template0|template1|\"} !=0",
     "legendFormat": "{{datname}}/{{mode}}"
    }
   ]
  },
  {
   "title": "PostgreSQL Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_deadlocks{instance=\"$database\",datname!~\"postgres|template0|template1\"}[5m])",
     "legendFormat": "{{datname}}.deadlocks"
    }
   ]
  },
  {
   "title": "PostgreSQL Deadlocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "pg_stat_long_runtime{instance=\"$database\"}",
     "legendFormat": "PID: {{pid}}"
    }
   ]
  },
  {
   "title": "Tuple Updated",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_updated{instance=\"$database\",datname!~\"postgres|template0|template1\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Tuple Deleted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_deleted{instance=\"$database\",datname!~\"postgres|template0|template1\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Tuple Inserted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_tup_inserted{instance=\"$database\",datname!~\"postgres|template0|template1\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{instance=\"$database\",datname!~\"postgres|template0|template1\"}/(pg_stat_database_blks_read{instance=\"$database\",datname!~\"postgres|template0|template1\"}+pg_stat_database_blks_hit{instance=\"$database\",datname!~\"postgres|template0|template1\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{instance=\"$database\"}[5m])",
     "legendFormat": "checkpoint_sync_time"
    },
    {
     "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{instance=\"$database\"}[5m])",
     "legendFormat": "checkpoint_write_time"
    }
   ]
  }
 ]
}